#!/bin/bash
# Quick Docker Compose v2 Reference Guide

echo "🏥 HHS Patient Portal - Docker Quick Reference"
echo ""
echo "📋 Build & Deployment:"
echo "   ./docker-build.sh build       # Build Docker image"
echo "   ./docker-build.sh start       # Start all services"
echo "   ./docker-build.sh stop        # Stop all services"
echo "   ./docker-build.sh restart     # Restart all services"
echo ""
echo "📊 Monitoring:"
echo "   ./docker-build.sh status      # Show service status + resources"
echo "   ./docker-build.sh logs api    # View API logs"
echo "   ./docker-build.sh logs db     # View database logs"
echo "   docker compose ps             # Service status"
echo "   docker stats                  # Real-time resource usage"
echo ""
echo "🔧 Maintenance:"
echo "   ./docker-build.sh clean       # Remove volumes (keep containers)"
echo "   ./docker-build.sh reset       # Hard reset (remove everything)"
echo "   docker compose down           # Stop all services"
echo ""
echo "🧪 Testing:"
echo "   curl http://localhost:3000/health          # API health"
echo "   curl http://localhost:80/                  # Frontend"
echo "   docker exec -it hhs-api bash               # Shell into API"
echo "   docker exec -it hhs-postgres psql -U postgres  # Database shell"
echo ""
echo "📝 Configuration:"
echo "   .env                          # Environment variables"
echo "   docker-compose.yml            # Service definitions"
echo "   Dockerfile                    # Container image definition"
echo ""
echo "✨ Modern Features:"
echo "   ✓ Docker Compose v2 (plugin) - more reliable"
echo "   ✓ Auto-restart on failure    - better uptime"
echo "   ✓ Health checks              - auto-recovery"
echo "   ✓ Resource monitoring        - better debugging"
echo "   ✓ Non-root containers        - improved security"
echo ""
